openapi: 3.0.1
info:
  title: OpenAPIGateway
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rostislav.pridal@jamf.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: /v1
paths:
  '/customer/{externalCustomerId}':
    get:
      tags:
        - Customer
      summary: Get customer detail by external customer id
      operationId: getCustomerByExternalCustomerId
      parameters:
        - name: externalCustomerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            text/json:
              schema:
                $ref: '#/components/schemas/CustomerRes'
        '404':
          description: externalCustomerId doesn't exist
  '/activation-profiles':
    get:
      tags:
        - Activation
      summary: Get all activation profiles for given customer
      operationId: getActivationProfilesUsingGET
      parameters:
        - name: customerId
          in: query
          description: customerId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/json:
              schema:
                $ref: '#/components/schemas/ActivationProfiles'
        '404':
          description: Customer Id doesn't exist
  '/configuration-profiles/{code}':
    get:
      tags:
        - Activation
      summary: Generate profile templates for importing into UEM
      operationId: generateUsingGET_1
      parameters:
        - name: code
          in: path
          description: code
          required: true
          schema:
            type: string
        - name: customerId
          in: query
          description: customerId
          required: true
          schema:
            type: string
        - name: uem
          in: query
          description: uem
          required: true
          schema:
            type: string
            enum:
            - JAMF_SCHOOL
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Customer Id or Activation profile doesn't exist
  '/devices':
    get:
      tags:
        - Device
      parameters:
        - name: customerId
          in: query
          description: customerId
          required: true
          example: 4fefddae-90a2-41ac-922f-75c3167668ed
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/json:
             schema:
              $ref: '#/components/schemas/Devices'
components:
  schemas:
    CustomerRes:
      type: object
      properties:
        id:
          type: string
          example: 4fefddae-90a2-41ac-922f-75c3167668ed
        externalId:
          type: string
          example: f09ed809-9c53-425d-8ec9-93ea6fb49b3a
    DeviceRes:
      type: object
      properties:
        id:
          type: string
          example: a71f32aa-4583-41cc-80b7-0bbe8b66f9fd
        externalId:
          type: string
          example: b29997aa-dfb4-4ccd-9cff-c2af25f4e301
        createdAt:
          type: integer
          format: int64
          description: timestamp ms in UTC
          example: 1643893993
        lastTraffic:
          type: integer
          format: int64
          description: TBD
          example: 1643893993
    Devices:
      type: object
      properties:
        activeDeviceCount:
          type: integer
          format: int64
        devices:
          type: array
          items:
            $ref: '#/components/schemas/DeviceRes'  
    ActivationProfiles:
      title: ActivationProfiles
      type: object
      properties:
        activeProfilesCount:
          type: integer
          format: int64
        allProfilesCount:
          type: integer
          format: int64
        lastActivation:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ActivationProfileRes'
    ActivationProfileRes:
      title: ActivationProfileRes
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        enabled:
          type: boolean
  links: {}
  callbacks: {}
security: []