openapi: 3.0.1
info:
  title: OpenAPIGateway
  description: ''
  termsOfService: http://swagger.io/terms/
  contact:
    email: rostislav.pridal@jamf.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /v1
paths:
  /customer/{externalCustomerId}:
    get:
      tags:
        - Customer
      summary: Get customer detail by external customer id
      operationId: getCustomerByExternalCustomerId
      parameters:
        - name: externalCustomerId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: externalCustomerId doesn't exist
  /enrollment:
    get:
      tags:
      - Enrollment
      summary: Get all active enrollment links for given customer
      operationId: getEnrollmentLinksUsingGET
      parameters:
      - name: customerId
        in: query
        description: customerId
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EnrollmentLinks'         
          
  /enrollment/{code}/profiles:
    get:
      tags:
        - Enrollment
      summary: Generate profile templates for importing into UEM
      operationId: generateUsingGET_1
      parameters:
        - name: code
          in: path
          description: code
          required: true
          schema:
            type: string
        - name: customerId
          in: query
          description: customerId
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Customer Id or Activation profile doesn't exist 
          
components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: string
          example: '4fefddae-90a2-41ac-922f-75c3167668ed'
        extenralCustomerId:
          type: string
          example: 'f09ed809-9c53-425d-8ec9-93ea6fb49b3a'
    EnrollmentLinks:
      title: EnrollmentLinks
      type: object
      properties:
        activeLinksCount:
          type: integer
          format: int64
        allLinksCount:
          type: integer
          format: int64
        lastEnrollment:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/EnrollmentLinkRes'
    EnrollmentLinkRes:
      title: EnrollmentLinkRes
      type: object
      properties:
        code:
          type: string
