openapi: 3.0.1
info:
  title: OpenAPIGateway
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rostislav.pridal@jamf.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: /v1
paths:
  '/customer/{externalCustomerId}':
    $ref: 'paths/customer@{externalCustomerId}.yaml'
  /enrollment:
    $ref: paths/enrollment.yaml
  '/enrollment/{code}/profiles':
    $ref: 'paths/enrollment@{code}@profiles.yaml'
